In [2]:
import numpy as np

In [3]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [4]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [5]:
def derivativeSig(z):
    return sig(z)*(1 - sig(z))

In [16]:
# no hidden layer weights
weights = 2* np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1
lr = 0.1
weights, bias


(array([[ 0.79357691],
        [-0.3238048 ]]), array([-0.15933083]))

In [17]:
# forward propagation without any hidden layer
for iter in range(10000):
    output0 = X
    output = sig(np.dot(output0, weights) + bias)

    first_term = output - Y
    input_for_last_layer = np.dot(output0, weights) + bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term * second_term
    first_two.shape

    changes = np.dot(first_two.T, output0)
    ##converted loop to 
    weights = weights - lr*changes
    bias_change = 0.0
    for j in range(4):
        bias_change += first_two[j][0] * 1
    bias = bias - lr * bias_change
output = sig(np.dot(X, weights) + bias)
weights, bias, output

(array([[  -0.3317688 ,    3.64441217],
        [-102.76797095,    2.20119388]]),
 array([-4.0321788]),
 array([[1.74265739e-02, 1.74265739e-02],
        [4.14270776e-47, 1.38120984e-01],
        [1.25680762e-02, 4.04255055e-01],
        [2.97302758e-47, 8.59775579e-01]]))

In [11]:
first_two.shape, output0.shape

((4, 2), (4, 2))