In [1]:
import numpy as np

In [2]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [3]:
def derSig(z):
    return sig(z)* (1 - sig(z))

In [4]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,1,1,0]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [5]:
wh = 2 * np.random.random((2, 2)) - 1
wout = 2 * np.random.random((2, 1)) - 1
bh = 2 * np.random.random((1,2)) - 1
bout = 2 * np.random.random((1,1)) - 1


In [20]:
def forward(x, wh, wout, bh, bout):
    output0 = x
    hidden_layer_input = np.dot(output0, wh) + bh
    hidden_layer_output = sig(hidden_layer_input)
    
    output_layer_input = np.dot(hidden_layer_output, wout) + bout
    final_output = sig(output_layer_input)
    return final_output




[[0.01267342]
 [0.98904385]
 [0.98910116]
 [0.0114127 ]]


In [25]:
def train(x, y, wh, wout, bh, bout, epochs, lr):
    for i in range(epochs):
        output0 = x
        hidden_layer_input = np.dot(output0, wh) + bh
        hidden_layer_output = sig(hidden_layer_input)
    
        output_layer_input = np.dot(hidden_layer_output, wout) + bout
        final_output = sig(output_layer_input)
        
        first_term_output = final_output - y
        second_term_output = derSig(output_layer_input)
        first_two_output = first_term_output*second_term_output
        
        first_term_hidden_layer = np.dot(first_two_output, wout.T)#why mult
        second_term_hidden_layer = derSig(hidden_layer_input)
        first_two_hidden = first_term_hidden_layer*second_term_hidden_layer
        
        
        changes_wh = np.dot(output0.T, first_two_hidden)
        changes_wout = np.dot(hidden_layer_output.T, first_two_output)
        
        changes_bh = np.sum(first_two_hidden, axis = 0)
        change_bout = np.sum(first_two_output, axis = 0)
        
        wh = wh - lr*changes_wh
        wout = wout - lr*changes_wout
        bout = bout - lr*change_bout
        bh = bh - lr * changes_bh
        
    return wh, wout, bh, bout




In [8]:
wh, wout, bh, bout = train(X, Y, wh, wout,bh, bout, 10000, 1)

In [13]:
forward(X, wh, wout, bh, bout)

(4, 1) (4, 1) (4, 2)


array([[0.01267342],
       [0.98904385],
       [0.98910116],
       [0.0114127 ]])

In [15]:
wout,bout

(array([[10.18839026],
        [10.07747191]]), array([[-5.01208089]]))

In [16]:
wh, bh

(array([[-6.15309994,  6.36774276],
        [ 5.92599467, -6.49375866]]), array([[-3.27853352, -3.53113425]]))

In [28]:
a = np.array([[1,2,3],[4,5,6]])
b = np.sum(a, axis = 0, keepdims=True)
b,b.shape


(array([[5, 7, 9]]), (1, 3))